name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    name: RuboCop Analysis
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install RuboCop
        run: gem install rubocop
      - name: Run RuboCop
        run: rubocop -x

  success_job:
    name: Success Notification
    runs-on: ubuntu-latest
    needs: rubocop  # This ensures vagrant_validate runs second
    steps:
      - name: Notify Success
        run: echo "New code was successfully created.."
